CREATE TABLE T_CM_INST (
	ID  			VARCHAR(4),
	DESCRIPTION 	VARCHAR(40)
);

COMMENT ON TABLE 	T_CM_INST 				IS 'This table contains institutes';
COMMENT ON COLUMN 	T_CM_INST.ID 			IS 'Unique ID identifying institute';
COMMENT ON COLUMN 	T_CM_INST.DESCRIPTION 	IS 'Description of the institute';

CREATE UNIQUE INDEX I_CM_INST_ID ON T_CM_INST (ID);

ALTER TABLE T_CM_INST ADD 
	CONSTRAINT PK_CM_INST PRIMARY KEY USING INDEX I_CM_INST_ID;