CREATE TABLE T_CM_CALENDAR (
  	CL_ID    	NUMERIC(9)         	NOT NULL,
  	CL_TYPE  	NUMERIC(2)         	NOT NULL,
  	DESCX    	VARCHAR(255)				NOT NULL
);

COMMENT ON TABLE 	T_CM_CALENDAR 			IS 'This table contains available calendars';
COMMENT ON COLUMN 	T_CM_CALENDAR.CL_ID 	IS 'Unique ID identifying the calendar';
COMMENT ON COLUMN 	T_CM_CALENDAR.CL_TYPE 	IS 'Type of calendar';
COMMENT ON COLUMN 	T_CM_CALENDAR.DESCX 	IS 'Description of the calendar';

CREATE UNIQUE INDEX I_CM_CALENDAR_ID ON T_CM_CALENDAR (CL_ID);

ALTER TABLE T_CM_CALENDAR ADD 
	CONSTRAINT PK_CM_CALENDAR PRIMARY KEY USING INDEX I_CM_CALENDAR_ID;