CREATE TABLE T_CM_USER2ROLES (
	USER_ID	NUMERIC(10),
	ROLE_ID	NUMERIC(6)
);

COMMENT ON TABLE 	T_CM_USER2ROLES 			IS 'Table for linking users and roles';
COMMENT ON COLUMN 	T_CM_USER2ROLES.USER_ID 	IS 'User ID';
COMMENT ON COLUMN 	T_CM_USER2ROLES.ROLE_ID 	IS 'Role ID';

CREATE UNIQUE INDEX I_CM_USER2ROLES_UID2RID ON T_CM_USER2ROLES (USER_ID, ROLE_ID);

ALTER TABLE T_CM_USER2ROLES ADD 
	CONSTRAINT PK_CM_USER2ROLES PRIMARY KEY USING INDEX I_CM_USER2ROLES_UID2RID;