CREATE TABLE T_CM_ATM_GROUP (
	ID  			NUMERIC(10),
  	NAME          	VARCHAR(40)			NOT NULL,
  	TYPE_ID         NUMERIC(3)			NOT NULL,
  	DESCRIPTION   	VARCHAR(200)
);

COMMENT ON TABLE 	T_CM_ATM_GROUP 					IS 'This table contains ATM groups';
COMMENT ON COLUMN 	T_CM_ATM_GROUP.ID 				IS 'Unique ID identifying ATM group';
COMMENT ON COLUMN 	T_CM_ATM_GROUP.NAME 			IS 'Group name';
COMMENT ON COLUMN 	T_CM_ATM_GROUP.TYPE_ID 			IS 'Group type ID';
COMMENT ON COLUMN 	T_CM_ATM_GROUP.DESCRIPTION 		IS 'Group description';


CREATE UNIQUE INDEX I_CM_ATM_GROUP_ID ON T_CM_ATM_GROUP (ID);

ALTER TABLE T_CM_ATM_GROUP ADD 
	CONSTRAINT PK_CM_ATM_GROUP PRIMARY KEY USING INDEX I_CM_ATM_GROUP_ID;
