INSERT INTO T_CM_USER_STATUS (ID, DESCRIPTION) VALUES (1, 'Global Administrator');
INSERT INTO T_CM_USER_STATUS (ID, DESCRIPTION) VALUES (2, 'Local Administrator');
INSERT INTO T_CM_USER_STATUS (ID, DESCRIPTION) VALUES (3, 'User');

COMMIT;