INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1001,'CM_FORMS_MONITORING','Access to monitoring');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1002,'CM_FORMS_FORECASTING','Access to forecasting');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1003,'CM_FORMS_REPORTS','Access to reports');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1004,'CM_FORMS_SETTINGS','Access to general settings');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1005,'CM_FORMS_SETTINGS_CURRENCIES','Access to settings of currencies');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1006,'CM_FORMS_SYSTEM_USERS','Access to users');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1007,'CM_FORMS_SYSTEM_ROLEGROUPS','Access to role groups');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1008,'CM_FORMS_SYSTEM_INSTS','Access to institutions');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1030,'CM_VIEW_ALL_GROUPS','View all ATM groups');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1031,'CM_VIEW_ATM_OF_OTHER_USERS','View ATM groups of other users');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1032,'CM_SENIOR_ANALYST','Supervisor');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1033,'CM_ANALYST','Analyst');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1034,'CM_VIEW_GROUPS_OF_SUBORDINANTS','View ATM groups of subordinate users');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1035,'CM_MONITORING_ACTUALIZE','Actualize ATM state');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1036,'CM_CURRENCIES_MODIFY','Currencies modification');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1037,'CM_CALENDAR_MODIFY','Calendar modification');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1038,'CM_ATM_MODIFY','ATM information modification');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1039,'CM_ATM_SETTINGS_MODIFY','ATM settings modification');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1040,'CM_ATM_GROUP_MODIFY','ATM group modification');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1041,'CM_ATM_ATTR_GROUP_MODIFY','ATM attributes group modification');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1042,'CM_ANALYST_GROUP_MODIFY','Analyst group modification');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1043,'CM_TASK_MODIFY','Scheduled task modification');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1044,'CM_TASK_RUN','Scheduled task execution');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1045,'CM_INST_MODIFY','Institution modification');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1046,'CM_USER_DATA_MODIFY','Modify user data');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1049,'CM_USER_CHANGE_PASSWORD','Change password');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1050,'CM_ROLE_GROUP_MODIFY','Modify role group');

INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1009,'CM_FORMS_SYSTEM_APP_PARAMS','Access to apllication parameters');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1010,'CM_FORMS_OPTIMIZATION','Access to data analysis');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1011,'CM_FORMS_SYSTEM_AUDIT','Access to audit');

INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1051,'CM_VIEW_ALL_ENC_TICKETS','View all replenishment tickets');
INSERT INTO T_CM_ROLE (ID,NAME,DESCRIPTION) VALUES(1012,'CM_FORMS_ROUTES','Access to replenishment routes');

COMMIT;