ALTER TABLE T_CM_CASHIN_STAT ADD CONSTRAINT FK_CM_CASHIN_STAT_AID 	FOREIGN KEY (ATM_ID) 				REFERENCES T_CM_ATM (ATM_ID);
ALTER TABLE T_CM_CASHIN_STAT ADD CONSTRAINT FK_CM_CASHIN_STAT_CEID 	FOREIGN KEY (CASH_IN_ENCASHMENT_ID) REFERENCES T_CM_ENC_CASHIN_STAT (CASH_IN_ENCASHMENT_ID);
