CREATE TABLE T_CM_USER2USERS (
	USER_ID      	NUMERIC(10),
	SUB_USER_ID  	NUMERIC(10)
);

COMMENT ON TABLE 	T_CM_USER2USERS 				IS 'Table for linking users';
COMMENT ON COLUMN 	T_CM_USER2USERS.USER_ID 		IS 'User ID';
COMMENT ON COLUMN 	T_CM_USER2USERS.SUB_USER_ID 	IS 'Subordinate user ID';

CREATE UNIQUE INDEX I_CM_USER2USERS_UID2SUID ON T_CM_USER2USERS (USER_ID, SUB_USER_ID);

ALTER TABLE T_CM_USER2USERS ADD
	CONSTRAINT PK_CM_USER2USERS PRIMARY KEY USING INDEX I_CM_USER2USERS_UID2SUID;