CREATE TABLE T_CM_ROLE_GROUP (
	ID  			NUMERIC(10),
  	NAME          	VARCHAR(40)	NOT NULL,
  	DESCRIPTION   	VARCHAR(200)
);


COMMENT ON TABLE 	T_CM_ROLE_GROUP 				IS 'This table conatins role groups';
COMMENT ON COLUMN 	T_CM_ROLE_GROUP.ID 				IS 'Unique ID identifying role group';
COMMENT ON COLUMN 	T_CM_ROLE_GROUP.NAME 			IS 'Group name';
COMMENT ON COLUMN 	T_CM_ROLE_GROUP.DESCRIPTION 	IS 'Group description';


CREATE UNIQUE INDEX I_CM_ROLE_GROUP_ID ON T_CM_ROLE_GROUP (ID);


ALTER TABLE T_CM_ROLE_GROUP ADD 
	CONSTRAINT PK_CM_ROLE_GROUP PRIMARY KEY USING INDEX I_CM_ROLE_GROUP_ID;
