INSERT INTO T_CM_ATM_GROUP_TYPE (ID, DESCRIPTION) VALUES (1, 'Forecasting region');
INSERT INTO T_CM_ATM_GROUP_TYPE (ID, DESCRIPTION) VALUES (2, 'ATM model');
INSERT INTO T_CM_ATM_GROUP_TYPE (ID, DESCRIPTION) VALUES (4, 'Encashment cost');
INSERT INTO T_CM_ATM_GROUP_TYPE (ID, DESCRIPTION) VALUES (5, 'User''s group');

COMMIT;