CREATE FUNCTION TR_BUPD_CM_USER_TRIGGER_FUNCTION () RETURNS trigger AS  
'BEGIN 
NEW.ID := OLD.ID;
RETURN NEW;
END;'
 LANGUAGE  plpgsql;
CREATE TRIGGER TR_BUPD_CM_USER
BEFORE UPDATE ON T_CM_USER FOR EACH ROW
EXECUTE PROCEDURE TR_BUPD_CM_USER_TRIGGER_FUNCTION();
/