-- Supervisor roles: 
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1001);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1002);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1003);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1004);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1005);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1006);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1007);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1008);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1030);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1031);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1032);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1033);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1034);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1035);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1036);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1037);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1038);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1039);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1040);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1041);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1043);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-3,1044);
-- Analyst roles
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1001);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1002);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1003);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1004);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1005);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1033);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1035);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1036);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1037);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1039);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1041);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1043);
INSERT INTO T_CM_ROLE_GROUP2ROLES (ROLE_GROUP_ID,ROLE_ID) VALUES(-4,1044);

COMMIT;

