CREATE TABLE T_CM_ROUTE_DEPOT
(
  ID         NUMERIC(8) NOT NULL,
  INST_ID    VARCHAR(4) NOT NULL,
  STATE      VARCHAR(200),
  CITY       VARCHAR(200),
  STREET     VARCHAR(200),
  LONGITUDE  VARCHAR(20),
  LATITUDE   VARCHAR(20)
);

COMMENT ON TABLE T_CM_ROUTE_DEPOT IS 'This table contains information about Depots';

COMMENT ON COLUMN T_CM_ROUTE_DEPOT.ID IS 'Depot ID';

COMMENT ON COLUMN T_CM_ROUTE_DEPOT.INST_ID IS 'Institution ID';

COMMENT ON COLUMN T_CM_ROUTE_DEPOT.STATE IS 'State (region)';

COMMENT ON COLUMN T_CM_ROUTE_DEPOT.CITY IS 'City';

COMMENT ON COLUMN T_CM_ROUTE_DEPOT.STREET IS 'Street';

COMMENT ON COLUMN T_CM_ROUTE_DEPOT.LONGITUDE IS 'Depot coordinates Longitude';

COMMENT ON COLUMN T_CM_ROUTE_DEPOT.LATITUDE IS 'Depot coordinates Latitude';



ALTER TABLE T_CM_ROUTE_DEPOT ADD 
  CONSTRAINT T_CM_ROUTE_DEPOT_PK
  PRIMARY KEY
  (ID);
