CREATE TABLE T_CM_ROUTE_LOG
(
  ROUTE_ID  NUMERIC(4),
  LOG_DATE  TIMESTAMP,
  LOG_TYPE  NUMERIC(2),
  LOG_ID    NUMERIC(7),
  PARAMS    VARCHAR(500)
);

COMMENT ON TABLE T_CM_ROUTE_LOG IS 'This table contains Messages for Routing';

COMMENT ON COLUMN T_CM_ROUTE_LOG.ROUTE_ID IS 'Route ID';

COMMENT ON COLUMN T_CM_ROUTE_LOG.LOG_DATE IS 'Message Date';

COMMENT ON COLUMN T_CM_ROUTE_LOG.LOG_TYPE IS 'Message type';

COMMENT ON COLUMN T_CM_ROUTE_LOG.LOG_ID IS 'Message ID';

COMMENT ON COLUMN T_CM_ROUTE_LOG.PARAMS IS 'Comma-separated list of strings';
