CREATE TABLE T_CM_NOTIFICATION_MESSAGE
(
  ID            NUMERIC(4),
  CREATE_DATE   TIMESTAMP,
  USER_ID       NUMERIC(9),
  MESSAGE_TYPE  NUMERIC(3),
  PARAMS        VARCHAR(200),
  IS_NEW        NUMERIC(1)
);