CREATE TABLE T_CM_USER_PASSWORD_HISTORY (
  	USER_ID         NUMERIC(10),
  	PASSWORD_HASH	VARCHAR(89),
  	CREATION_DATE	TIMESTAMP
);

COMMENT ON TABLE 	T_CM_USER_PASSWORD_HISTORY 					IS 'This table contains users password change history';
COMMENT ON COLUMN 	T_CM_USER_PASSWORD_HISTORY.USER_ID 			IS 'User ID';
COMMENT ON COLUMN 	T_CM_USER_PASSWORD_HISTORY.PASSWORD_HASH 	IS 'Password hash';
COMMENT ON COLUMN 	T_CM_USER_PASSWORD_HISTORY.CREATION_DATE 	IS 'Date of password creation';

CREATE UNIQUE INDEX I_CM_UPH_UID2PH2CD ON T_CM_USER_PASSWORD_HISTORY (USER_ID, PASSWORD_HASH, CREATION_DATE);

ALTER TABLE T_CM_USER_PASSWORD_HISTORY ADD
	CONSTRAINT PK_CM_USER_PASSWORD_HISTORY PRIMARY KEY USING INDEX I_CM_UPH_UID2PH2CD;