ALTER TABLE T_CM_ROLE_GROUP2ROLES ADD CONSTRAINT FK_CM_RG2ROLES_RGID 	FOREIGN KEY (ROLE_GROUP_ID) 	REFERENCES T_CM_ROLE_GROUP (ID) ON DELETE CASCADE;
ALTER TABLE T_CM_ROLE_GROUP2ROLES ADD CONSTRAINT FK_CM_RG2ROLES_RID 	FOREIGN KEY (ROLE_ID) 			REFERENCES T_CM_ROLE (ID);

