CREATE TABLE T_CM_ENC_PERIOD (
  	ID                             NUMERIC(6) NOT NULL,
    ATM_ID                         NUMERIC(9) NOT NULL,
    DATE_FORTHCOMING_ENCASHMENT    TIMESTAMP,
    ENCASHMENT_TYPE                NUMERIC(1),
    FORECAST_RESP_CODE             NUMERIC(2) DEFAULT 0,
    CASH_IN_EXISTS                 NUMERIC(1) DEFAULT 0,
    EMERGENCY_ENCASHMENT           NUMERIC(1) DEFAULT 0
);


COMMENT ON TABLE T_CM_ENC_PERIOD IS 'This table contains planned encashments for period';
COMMENT ON COLUMN T_CM_ENC_PERIOD.ATM_ID IS 'Unique ID identifying ATM';
COMMENT ON COLUMN T_CM_ENC_PERIOD.CASH_IN_EXISTS IS 'Flag indicating whether cash in exists for ATM';
COMMENT ON COLUMN T_CM_ENC_PERIOD.DATE_FORTHCOMING_ENCASHMENT IS 'Date of planned replenishment';
COMMENT ON COLUMN T_CM_ENC_PERIOD.EMERGENCY_ENCASHMENT IS 'Flag indicating whether replenishment is emergency';
COMMENT ON COLUMN T_CM_ENC_PERIOD.ENCASHMENT_TYPE IS 'Cash in result of forecasting procedure';
COMMENT ON COLUMN T_CM_ENC_PERIOD.FORECAST_RESP_CODE IS 'Response code of cash out frorecasting procedure';
COMMENT ON COLUMN T_CM_ENC_PERIOD.ID IS 'Planned replenishment ID';

CREATE UNIQUE INDEX I_CM_ENC_PERIOD_EPI ON T_CM_ENC_PERIOD (ID);

ALTER TABLE T_CM_ENC_PERIOD ADD 
    CONSTRAINT PK_CM_ENC_PERIOD PRIMARY KEY USING INDEX I_CM_ENC_PERIOD_EPI;

