CREATE TABLE T_CM_ENC_CASHIN_STAT (
  	ATM_ID                 NUMERIC(9) 	NOT NULL,
  	CASH_IN_ENC_DATE       TIMESTAMP      			NOT NULL,
  	CASH_IN_ENCASHMENT_ID  NUMERIC(6)			NOT NULL
);

COMMENT ON TABLE 	T_CM_ENC_CASHIN_STAT 						IS 'This table contains loaded cash in replenishments';
COMMENT ON COLUMN 	T_CM_ENC_CASHIN_STAT.ATM_ID 				IS 'Unique ID identifying the ATM';
COMMENT ON COLUMN 	T_CM_ENC_CASHIN_STAT.CASH_IN_ENC_DATE 		IS 'Date of cash in replenishment';
COMMENT ON COLUMN 	T_CM_ENC_CASHIN_STAT.CASH_IN_ENCASHMENT_ID 	IS 'Internal Cash Management cash in replenishment identifier';

CREATE UNIQUE INDEX I_CM_ENC_CASHIN_STAT_CEI ON T_CM_ENC_CASHIN_STAT (CASH_IN_ENCASHMENT_ID);

ALTER TABLE T_CM_ENC_CASHIN_STAT ADD
  	CONSTRAINT PK_CM_ENC_CASHIN_STAT PRIMARY KEY USING INDEX I_CM_ENC_CASHIN_STAT_CEI;