CREATE TEMPORARY TABLE t_cm_temp_enc_plan_curr
    (enc_plan_id                    NUMERIC(6) NOT NULL,
    curr_code                      NUMERIC(3) NOT NULL,
    curr_summ                      NUMERIC(15) NOT NULL)
ON COMMIT DELETE ROWS;

COMMENT ON TABLE t_cm_temp_enc_plan_curr IS 'This table contains list of currencies that would be loaded on replenishment generated by forecasting for user-defined date.';
COMMENT ON COLUMN t_cm_temp_enc_plan_curr.curr_code IS 'Currency code';
COMMENT ON COLUMN t_cm_temp_enc_plan_curr.curr_summ IS 'Currency summ';
COMMENT ON COLUMN t_cm_temp_enc_plan_curr.enc_plan_id IS 'Planned replenishment ID';
